//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenBolgsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.BlogsLeave = new HashSet<BlogsLeave>();
        }
    
        public int article_Id { get; set; }
        public string article_Title { get; set; }
        public string article_Content { get; set; }
        public int article_Type { get; set; }
        public string article_ImgUrl { get; set; }
        public Nullable<int> article_CreatAdminId { get; set; }
        public string article_MakCode { get; set; }
        public string article_CreatDateTime { get; set; }
        public Nullable<bool> article_Status { get; set; }
        public string article_MakHtml { get; set; }
        public int article_PV { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ArticleType ArticleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogsLeave> BlogsLeave { get; set; }

       
    }
}
