//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenBolgsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int error_id { get; set; }
        public string error_content { get; set; }
        public System.DateTime error_createdatetime { get; set; }
    }
}
