//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenBolgsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operatelog
    {
        public int log_Id { get; set; }
        public string log_Content { get; set; }
        public System.DateTime log_CreatDataTime { get; set; }
        public int log_OperatelogAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
