//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenBolgsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BlogsLeave = new HashSet<BlogsLeave>();
        }
    
        public int user_Id { get; set; }
        public string user_Name { get; set; }
        public string user_PassWord { get; set; }
        public string user_ImgUrl { get; set; }
        public int user_Type { get; set; }
        public System.DateTime user_CreatDateTime { get; set; }
        public bool user_Status { get; set; }
        public string user_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogsLeave> BlogsLeave { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
